### ISSUE TITLE
Issues to resolve before next full site rebuild

### ISSUE THREAD

**Issue by clauswilke** [clauswilke/dataviz#50]
Issues to resolve before the next full site rebuild for public posting:
* [ ] #39 Explain correlation examples
* [ ] #40 Basic PCA examples
* [ ] #44 Discrepancy in the Okabe and Ito palette
* [ ] #47 Update iris figures in line drawings chapter
* [ ] #49 Rework data:ink ratio chapter
