### ISSUE TITLE
Things to be completed for final draft

### ISSUE THREAD

**Issue by clauswilke** [clauswilke/dataviz#57]
## New chapters

- [x] #52 Visualizing trends
- [x] #53 Visualizing uncertainty
- [x] #54 Visualizing geospatial data

## Substantially revised chapters

- [x] #63 Finalize directory of visualizations
- [x] #55 Revise "Handling overlapping points"
- [x] #48 Add section on memorable figures

## Minor issues

- [x] #59 Swap first and second figure in figure captions chapter.
- [x] #56 Redraw figures in image format chapter
- [x] #61 Revisit Tufte-style bar graphs
- [x] #62 Replace volcano image
- [x] #64 Fix sina plots
- [x] #65 Fix margins in ridgeline plots
- [x] #66 Attribute data sources in all figure captions
- [ ] #74 Add a beeswarm plot?

**Comment by steveharoz** [comment]
For uncertainty, it might be worth checking out this recent article - http://users.eecs.northwestern.edu/~jhullman/uncertainty_vis_eval.pdf

**Comment by clauswilke** [comment]
Thanks!

**Comment by clauswilke** [comment]
book is in production now.
